Changed version

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -2,32 +2,44 @@
 # process (which uses our internal CI system) this file is here for the benefit
 # of community developers git clones - see MDL-51458.
 
+# We currently disable Travis notifications entirely until https://github.com/travis-ci/travis-ci/issues/4976
+# is fixed.
 notifications:
-  email:
-    if: env(MOODLE_EMAIL) != no
+  email: false
 
 language: php
 
 os: linux
 
-dist: focal
+dist: xenial
 
 services:
     - mysql
-    - docker
+
+php:
+    # We only run the highest and lowest supported versions to reduce the load on travis-ci.org.
+    - 7.4
+    - 7.2
 
 addons:
-  postgresql: "12"
-  apt:
-    packages:
-      - postgresql-12
-      - postgresql-client-12
+  postgresql: "9.6"
 
-branches:
-  except:
-    - master
-    - /MOODLE_[0-9]+_STABLE/
-    - /^v[0-9]+\.[0-9]+\.[0-9]+.*/
+env:
+    # Although we want to run these jobs and see failures as quickly as possible, we also want to get the slowest job to
+    # start first so that the total run time is not too high.
+    #
+    # We only run MySQL on PHP 7.2, so run that first.
+    # CI Tests should be second-highest in priority as these only take <= 60 seconds to run under normal circumstances.
+    # Postgres is significantly is pretty reasonable in its run-time.
+
+    # Run CI Tests without running PHPUnit.
+    - DB=none     TASK=CITEST
+
+    # Run unit tests on Postgres
+    - DB=pgsql    TASK=PHPUNIT
+
+    # Perform an upgrade test too.
+    - DB=pgsql    TASK=UPGRADE
 
 jobs:
     # Enable fast finish.
@@ -36,35 +48,12 @@ jobs:
     fast_finish: true
 
     include:
-        # First all the lowest php ones (7.4)
+          # Run mysql only on highest - it's just too slow
         - php: 7.4
-          env: DB=none     TASK=CITEST
+          env: DB=mysqli   TASK=PHPUNIT
+          # Run grunt/npm install on highest version too ('node' is an alias for the latest node.js version.)
         - php: 7.4
-          env: DB=none     TASK=GRUNT
-
-        - if: env(MOODLE_DATABASE) = "pgsql" OR env(MOODLE_DATABASE) = "all" OR env(MOODLE_DATABASE) IS NOT present
-          php: 7.4
-          env: DB=pgsql    TASK=PHPUNIT
-
-        - if: env(MOODLE_DATABASE) = "mysqli" OR env(MOODLE_DATABASE) = "all"
-          php: 7.4
-          env: DB=mysqli   TASK=PHPUNIT
-
-        # Then, conditionally, all the highest php ones (8.1)
-        - if: env(MOODLE_PHP) = "all"
-          php: 8.1
-          env: DB=none     TASK=CITEST
-        - if: env(MOODLE_PHP) = "all"
-          php: 8.1
-          env: DB=none     TASK=GRUNT
-
-        - if: env(MOODLE_PHP) = "all" AND (env(MOODLE_DATABASE) = "pgsql" OR env(MOODLE_DATABASE) = "all" OR env(MOODLE_DATABASE) IS NOT present)
-          php: 8.1
-          env: DB=pgsql    TASK=PHPUNIT
-
-        - if: env(MOODLE_PHP) = "all" AND (env(MOODLE_DATABASE) = "mysqli" OR env(MOODLE_DATABASE) = "all")
-          php: 8.1
-          env: DB=mysqli   TASK=PHPUNIT
+          env: DB=none     TASK=GRUNT   NVM_VERSION='lts/carbon'
 
 cache:
     directories:
@@ -72,14 +61,8 @@ cache:
       - $HOME/.npm
 
 before_install:
-    - docker run -d -p 127.0.0.1:8080:80 --name exttests moodlehq/moodle-exttests
     # Avoid IPv6 default binding as service (causes redis not to start).
-    - sudo service redis-server start --bind 127.0.0.1
-
-env:
-  global:
-    - PGVER=12
-    - PGPORT=5433
+    sudo service redis-server start --bind 127.0.0.1
 
 install:
     - >
@@ -90,8 +73,7 @@ install:
             sudo service mysql stop
             sudo mv /var/lib/mysql /mnt/ramdisk
             sudo ln -s /mnt/ramdisk/mysql /var/lib/mysql
-            echo -e "[mysqld]\nskip-log-bin" | sudo tee -a /etc/mysql/my.cnf
-            sudo service mysql start
+            sudo service mysql restart
         fi
     - >
         if [ "$DB" = 'pgsql' ];
@@ -101,8 +83,7 @@ install:
             sudo service postgresql stop
             sudo mv /var/lib/postgresql /mnt/ramdisk
             sudo ln -s /mnt/ramdisk/postgresql /var/lib/postgresql
-            sudo service postgresql start
-            sh -c 'until pg_isready -p $PGPORT; do echo "Waiting for the DB to be up..."; sleep 2; done'
+            sudo service postgresql start 9.6
         fi
     - >
         if [ "$TASK" = 'PHPUNIT' ];
@@ -124,15 +105,14 @@ install:
     - >
         if [ "$TASK" = 'GRUNT' ];
         then
-            nvm install
-            nvm use
+            nvm install $NVM_VERSION ;
+            nvm use $NVM_VERSION ;
         fi
 
 before_script:
-    - echo 'max_input_vars=5000' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
     - phpenv config-rm xdebug.ini
     - >
-      if [ "$TASK" = 'PHPUNIT' ];
+      if [ "$TASK" = 'PHPUNIT' -o "$TASK" = 'UPGRADE' ];
       then
         # Copy generic configuration in place.
         cp config-dist.php config.php ;
@@ -156,11 +136,10 @@ before_script:
         then
           # Postgres-specific setup.
           sed -i \
-            -e "s%= 'username'%= 'travis'%" \
-            -e "s%'dbsocket'  => false%'dbsocket'  => true%" \
+            -e "s%= 'username'%= 'postgres'%" \
             config.php ;
 
-          psql -c 'CREATE DATABASE travis_ci_test;' -U travis;
+          psql -c 'CREATE DATABASE travis_ci_test;' -U postgres;
         fi
 
         if [ "$DB" = 'mysqli' ];
@@ -190,19 +169,14 @@ before_script:
           -e "/require_once/i \\\$CFG->phpunit_dataroot = '\/home\/travis\/roots\/phpunit';" \
           -e "/require_once/i \\\$CFG->phpunit_prefix = 'p_';" \
           config.php ;
-        # Enable test external resources
-        sed -i \
-          -e "/require_once/i \\define('TEST_EXTERNAL_FILES_HTTP_URL', 'http://127.0.0.1:8080');" \
-          -e "/require_once/i \\define('TEST_EXTERNAL_FILES_HTTPS_URL', 'http://127.0.0.1:8080');" \
-          config.php ;
-
         # Redis cache store tests
         sed -i \
           -e "/require_once/i \\define('TEST_CACHESTORE_REDIS_TESTSERVERS', '127.0.0.1');" \
           config.php ;
-        # Redis session tests
+        # Redis session tests, but not for PHP 7.2 and up. See MDL-60978 for more info.
+        redissession="define('TEST_SESSION_REDIS_HOST', '127.0.0.1');"
         sed -i \
-          -e "/require_once/i \\define('TEST_SESSION_REDIS_HOST', '127.0.0.1');" \
+          -e "/require_once/i \\${redissession}" \
           config.php ;
 
         # Initialise PHPUnit for Moodle.
@@ -232,7 +206,7 @@ before_script:
         # We need the official upstream for comparison
         git remote add upstream https://github.com/moodle/moodle.git;
 
-        git fetch upstream MOODLE_401_STABLE;
+        git fetch upstream MOODLE_39_STABLE;
         export GIT_PREVIOUS_COMMIT="`git merge-base FETCH_HEAD $TRAVIS_COMMIT`";
         export GIT_COMMIT="$TRAVIS_COMMIT";
         export UPSTREAM_FETCH_HEAD=`git rev-parse FETCH_HEAD`
@@ -241,6 +215,32 @@ before_script:
         export gitcmd=`which git`;
         export gitdir="$TRAVIS_BUILD_DIR";
         export phpcmd=`which php`;
+      fi
+
+    ########################################################################
+    # Upgrade test
+    ########################################################################
+    - >
+      if [ "$TASK" = 'UPGRADE' ];
+      then
+        # We need the official upstream.
+        git remote add upstream https://github.com/moodle/moodle.git;
+
+        # Checkout 30 STABLE branch (the first version compatible with PHP 7.x)
+        git fetch upstream MOODLE_30_STABLE;
+        git checkout MOODLE_30_STABLE;
+
+        # Perform the upgrade
+        php admin/cli/install_database.php --agree-license --adminpass=Password --adminemail=admin@example.com --fullname="Upgrade test" --shortname=Upgrade;
+
+        # Return to the previous commit
+        git checkout -;
+
+        # Perform the upgrade
+        php admin/cli/upgrade.php --non-interactive --allow-unstable ;
+
+        # The local_ci repository can be used to check upgrade savepoints.
+        git clone https://github.com/moodlehq/moodle-local_ci.git local/ci ;
       fi
 
 script:
@@ -268,10 +268,19 @@ script:
         git diff --cached --exit-code ;
       fi
 
-after_script:
+    ########################################################################
+    # Upgrade test
+    ########################################################################
     - >
-      if [ "$TASK" = 'PHPUNIT' ];
+      if [ "$TASK" = 'UPGRADE' ];
       then
-        EXTTESTS_HITS=$(docker logs exttests 2>&1 | grep -Fv -e 'AH00558' -e '[pid 1]' | wc -l)
-        echo -e "\nTest local resources number of hits: ${EXTTESTS_HITS}.\n"
+        cp local/ci/check_upgrade_savepoints/check_upgrade_savepoints.php ./check_upgrade_savepoints.php
+        result=`php check_upgrade_savepoints.php`;
+        # Check if there are problems
+        count=`echo "$result" | grep -P "ERROR|WARN" | wc -l` ;
+        if (($count > 0));
+        then
+          echo "$result"
+          exit 1 ;
+        fi
       fi
